### ISSUE TITLE
Missing First Character for Theorems

### ISSUE THREAD

**Issue by aegraue** [dev-aditya/LaTeX-template#1]
Hello, I'm a big fan of your notes package and I have just started using it for my own math notes. The only issue I'm having is that the first letter of anything in any of the environments keep getting dropped. I feel like it is probably user error rather than an issue with the package, but I figured I'd ask just in case you knew what I was doing wrong. Thanks for you awesome work.

**Comment by aegraue** [comment]
Well I figured out what I'm doing wrong; I had just gone from a traditional math environment to yours and the issue only appears when the theorem/definition is unnamed. There's an easy fix with search and replace as I have just copied and pasted in 1500 lines of notes and I'd rather not have to name everything specifically. Just out of curiosity, do you know if there is a way to make this work without having to name things?

**Comment by aegraue** [comment]
Oh my. Ignore all of this. I feel awfully silly. I should have read you example code better.

**Comment by dev-aditya** [comment]
Yeah you need to add the label `{thm:label}` after every colored environment you define. Having a name for an environment is not compulsory.
