### ISSUE TITLE
How to Have Custom Names for my Definitions

### ISSUE THREAD

**Issue by TrevorBushnell** [dev-aditya/LaTeX-template#2]
I would like to have custom names for my definitions whenever I create a new destination environment. I am able to do this with an added optional parameter when creating propositions but I cannot seem to get it to output with definitions using the same syntax. I'm sure this was error on my end so I was wondering if you could be a bit more clear on the syntax for having custom names for each definition, proof, proposition, etc? Thanks again for your awesome template.

**Comment by TrevorBushnell** [comment]
I'm really stupid, I have no clue why that wasn't working before but it works now. Sorry for the inconvenience. However, is there a way to remove the number associated with the definition (i.e. if I make a new definition within 1.1 it's called `Definition 1.1.x [INSERT CUSTOM TITLE HERE]`

**Comment by dev-aditya** [comment]
You can tweak the `\renewcommand{\thedef}{\arabic{chapter}.\arabic{section}.\arabic{def}}` according to your convenience (its below the `\newcounter{def}[subsection]\setcounter{def}{0}`). 

Thanks for pointing out the issue. I also noticed the same bug,, the numbering for the colored framed boxes are same if one defines them in the same section and its subsection. I'll look into this and try to fix this asap.

**Comment by dev-aditya** [comment]
Changed the `\newcounter` to set the value back to 1 if section changes (previously it was subsection)
