### ISSUE TITLE
Indicate required packages

### ISSUE THREAD

**Issue by martja** [dev-aditya/LaTeX-template#3]
I found it hard to use locally, because I had to find all the required packages to install by looking through the files + trial and error. It would be helpful if you included a list of required packages in your README.

**Comment by dev-aditya** [comment]
Hey @martja! Thanks for creating an Issue. 

If you are on Windows and using MiKTeX then it automatically installs the required packages for you. 
And if you are using Linux(Debian based distro), then I'll suggest using TeX Live full installation (I don't know if it auto installs required packages).
On my PC I simply run `sudo apt-get install texlive-full` and everything works smooth (it takes a lot of time to download and install). 
I've never used a Mac, so can't comment on that. 

Thanks for the suggestion. I'll include a list of required packages asap. 😄  

If you think it didn't help. Then you can reopen the issue.
