### ISSUE TITLE
1st letter loss in definition, theorem, proposition, corollary, lemma

### ISSUE THREAD

**Issue by suniyao** [dev-aditya/LaTeX-template#4]
When texing definition, theorem, proposition, corollary, lemma (excluding problem and proof), if you do not label them, the first letter you type will not be found in the pdf compiled.

e.g.: if you type 
`\begin{definition}[Row-Equivalent]`
`If one can obtain augmented matrix $B$ from augmented matrix $A$  via a series of elementary row operations, we say that $A$ and $B$ are \textbf{row-equivalent}.`
`\end{definition}`
 
The first letter "I" will be lost after compiling.

To solve this problem, you can press `enter` to change a line after typing `\begin{definition}[Row-Equivalent]`
to make it like this:
`\begin{definition}[Row-Equivalent]`

`If one can obtain augmented matrix $B$ from augmented matrix $A$  via a series of elementary row operations, we say that $A$ and $B$ are \textbf{row-equivalent}.`
`\end{definition}`

or to add label to it:
`\begin{definition}[Row-Equivalent]{def: row-equivalent}`
`If one can obtain augmented matrix $B$ from augmented matrix $A$  via a series of elementary row operations, we say that $A$ and $B$ are \textbf{row-equivalent}.`
`\end{definition}`
will make the first letter come up again.

**Comment by dev-aditya** [comment]
Thank you for raising this issue @PLASTA0728. I intentionally made labels compulsory in my template to reduce confusion while writing notes. However, if you prefer to omit the label name, you can do so by leaving the label field empty. For example:

```
\begin{definition}[Row-Equivalent]{}
If one can obtain augmented matrix $B$ from augmented matrix $A$  
via a series of elementary row operations, we say that $A$ and $B$ are \textbf{row-equivalent}.
\end{definition} 
```

You can also remove the compulsory label feature by manually editing the  [`color-env.sty`](https://github.com/dev-aditya/LaTeX-template/blob/main/Fancy-Book/package/color-env.sty)  file.

I hope this helps! Please let me know if you have any other comments. :smile:
